
services:
  flightbookingapi:
    image: flightbookingapi
    build:
      context: ./flightbookingapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
